/// Criar turma:
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "Banco de Dados",
    "modulo": 0
}

### // Criar estudante:
POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome": "Vini Junior",
    "email": "malvadeza@gmail.com.br",
    "data_nasc": "1991-03-15",
    "turma_id": "0.23113908740604372"
}

### // Criar docente:
POST http://localhost:3003/docente
Content-Type: application/json

{
    "nome": "Silvia",
    "email": "silvia@professora.com.br",
    "data_nasc": "1985-04-20",
    "turma_id": "0.6075049461144448"
}