/// CRIAR TURMA:
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "Azure"
}

### // LISTAR TURMAS:
GET http://localhost:3003/turma


### // ALTERAR MÓDULO DA TURMA:
PUT http://localhost:3003/turma/0.9484926436624486
Content-Type: application/json

{
    "modulo": 1
}



### // CRIAR ESTUDANTE:
POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome": "Flavinho",
    "email": "dopneu@gmail.com.br",
    "data_nasc": "1997-11-20",
    "turma_id":"0.5064846596933097"
}

### /// INSERIR HOBBY:
POST http://localhost:3003/hobby
Content-Type: application/json

{
    "estudante_id":"0.30619681600427895",
    "hobbies": [
        {"Hobby": "jogar futebol"}
    ]
}

### // FILTRAR ESTUDANTE PELO NOME COMPLETO:
GET http://localhost:3003/estudante/"Anitta"

### // ALTERAR TURMA DE UM DETERMINADO ESTUDANTE:
PUT http://localhost:3003/estudante/0.8097187227816469
Content-Type: application/json

{
    "turma_id": "0.9484926436624486"
}

### // FILTRAR ESTUDANTES QUE TENHAM O MESMO HOBBY:
GET http://localhost:3003/estudante/hobby/"jogar futebol"





### // CRIAR DOCENTE:
POST http://localhost:3003/docente
Content-Type: application/json

{
    "nome": "Hebe",
    "email": "hebe@professor.com.br",
    "data_nasc": "1957-02-10",
    "turma_id": "0.27275071045677013"
}

### /// INSERIR ESPECIALIDADE:W
POST http://localhost:3003/especialidade
Content-Type: application/json

{
    "docente_id":"0.7788297860724316",
    "especialidades": [
        {"especialidade": "Phyton"}
    ]
}

### // FILTRAR LISTA DE DOCENTES:
GET http://localhost:3003/docente

### // ALTERAR TURMA DE UM DOCENTE:
PUT http://localhost:3003/docente/0.910779734382184
Content-Type: application/json

{
    "turma_id":"0.23113908740604372"
}




